export const CardData = [
  {
    id: 1,
    itemCategory: "Laptop",
    itemDescription: [
      {
        brand: "Apple",
        img: "images/uochiuSefu.jpg",
        tipprocesor: "M1",
        modelPlacaVideo: "nVidia 7800",
        nrNucleeProcesor: "8",
        model: "MacBook Air",
        CapacitateMemorie: "8",
        TipLaptop: "Ultraportabil",
        ProducatorProcesor: "Apple",
        Pret: "5000",
        DiagonalaDisplay: "13",
        TipStocare: "SSD",
        capacitateStocare: "512 GB",
        TipPlacaVideo: "Dedicata",
        nrNucleePlacaVideo: "10",
        SistemDeOperare: "Mac OS",
        RezolutieDisplay: "3072 x 1920",
        TouchScreen: "Nu",
        TehnologiiDisplay: "Retina",
        Greutate: "1.5kg",
        Culoare: ["Argintiu", "Verde"],
      },
      {
        brand: "Apple",
        img: "images/uochiuSefu.jpg",
        tipprocesor: "M1",
        modelPlacaVideoIntegrata: "Intel 5",
        nrNucleeProcesor: "8",
        model: "MacBook Air",
        CapacitateMemorie: "8",
        TipLaptop: "Ultraportabil",
        ProducatorProcesor: "Apple",
        Pret: "5000",
        DiagonalaDisplay: "13",
        TipStocare: "SSD",
        capacitateStocare: "512",
        TipPlacaVideo: "Dedicata",
        nrNucleePlacaVideo: "10",
        SistemDeOperare: "Mac OS",
        RezolutieDisplay: "3072 x 1920",
        TouchScreen: "Nu",
        TehnologiiDisplay: "Retina",
        Greutate: "1.5kg",
        Culoare: "Verde",
      },
    ],
  },
];
