export const CardData = [
  {
    id: 1,
    itemCategory: "Laptop",
    itemDescription: [
      {
        brand: "Apple",
        img: "images/uochiuSefu.jpg",
        tipprocesor: "M1",
        modelPlacaVideo: [
          {
            id: 8,
            numePlacaVideo: "nVidia 7800",
          },
          {
            id: 9,
            numePlacaVideo: "nVidia 8800 TI",
          },
        ],
        nrNucleeProcesor: "8",
        model: "MacBook Air",
        CapacitateMemorie: "8",
        TipLaptop: "Ultraportabil",
        ProducatorProcesor: "Apple",
        Pret: "5000",
        DiagonalaDisplay: "13",
        TipStocare: "SSD",
        capacitateStocare: "512",
        TipPlacaVideo: "Dedicata",
        nrNucleePlacaVideo: "10",
        SistemDeOperare: "Mac OS",
        RezolutieDisplay: "3072 x 1920",
        TouchScreen: "Nu",
        TehnologiiDisplay: "Retina",
        Greutate: "1.5kg",
        Culoare: ["Argintiu", "Verde"],
      },
    ],
  },
  {
    id: 2,
    itemCategory: "Laptop",
    itemDescription: [
      {
        brand: "Apple",
        img: "images/uochiuSefu.jpg",
        tipprocesor: "M1",
        modelPlacaVideoIntegrata: ["Intel 3", "Intel 5"],
        nrNucleeProcesor: "8",
        model: "MacBook Air",
        CapacitateMemorie: "8",
        TipLaptop: "Ultraportabil",
        ProducatorProcesor: "Apple",
        Pret: "5000",
        DiagonalaDisplay: "13",
        TipStocare: "SSD",
        capacitateStocare: "512",
        TipPlacaVideo: "Dedicata",
        nrNucleePlacaVideo: "10",
        SistemDeOperare: "Mac OS",
        RezolutieDisplay: "3072 x 1920",
        TouchScreen: "Nu",
        TehnologiiDisplay: "Retina",
        Greutate: "1.5kg",
        Culoare: ["Argintiu", "Verde"],
      },
    ],
  },
];
